### ISSUE TITLE
💡 [FEATURE] - Create a Workflow for First PR and First Issue

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Hacktoberfest-Projects-Hub#30]
### Description:
Develop a workflow to acknowledge and celebrate the creators of the first Pull Request (PR) and the first Issue in our project. This workflow should be designed to recognize their contributions and encourage further participation.

### Tasks:
- [ ] Create the workflow for the first PR and first Issue using a `.yml` file.
- [ ] Add the created workflow to the `.github/workflows` directory.
- [ ] Test the workflow to ensure it functions as intended.

**Comment by Petsamuel** [comment]
Assign issue to me

**Comment by Pinaka-Pani-18** [comment]
Assigned to you @Petsamuel, you can start working on the issue.
